//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusiBuy.Common.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusiBuy.Common.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been {0} successfully..
        /// </summary>
        public static string ActionStatus {
            get {
                return ResourceManager.GetString("ActionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been activated successfully..
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added successfully..
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Enter/Select different value..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is available..
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cancelled successfully..
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be added..
        /// </summary>
        public static string CannotBeAdded {
            get {
                return ResourceManager.GetString("CannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be deleted..
        /// </summary>
        public static string CannotBeDeleted {
            get {
                return ResourceManager.GetString("CannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} combination with this {1} already exists. Try to choose different value..
        /// </summary>
        public static string CombinationExists {
            get {
                return ResourceManager.GetString("CombinationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your inquiry! It has been submitted successfully..
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count saved successfully!.
        /// </summary>
        public static string CountSave {
            get {
                return ResourceManager.GetString("CountSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Can&apos;t Save..
        /// </summary>
        public static string CountUnSave {
            get {
                return ResourceManager.GetString("CountUnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} had been successfully updated, changes will be in effect on your next login..
        /// </summary>
        public static string CurrentRoleUpdated {
            get {
                return ResourceManager.GetString("CurrentRoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted successfully..
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not uploaded..
        /// </summary>
        public static string DocumentNotUpload {
            get {
                return ResourceManager.GetString("DocumentNotUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document uploaded successfully..
        /// </summary>
        public static string DocumentUploaded {
            get {
                return ResourceManager.GetString("DocumentUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The record has been deleted from the system..
        /// </summary>
        public static string Drop {
            get {
                return ResourceManager.GetString("Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is duplicate..
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t exist. Please enter another email..
        /// </summary>
        public static string EmailDoesntExists {
            get {
                return ResourceManager.GetString("EmailDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was not sent..
        /// </summary>
        public static string EmailNotSuccess {
            get {
                return ResourceManager.GetString("EmailNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been sent successfully..
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured, Please try again..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploaded Successfully..
        /// </summary>
        public static string ExcelAdded {
            get {
                return ResourceManager.GetString("ExcelAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is expired..
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} request has been {1} successfully..
        /// </summary>
        public static string ExtendRequest {
            get {
                return ResourceManager.GetString("ExtendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please filled all the required fileds..
        /// </summary>
        public static string FillUpAllFields {
            get {
                return ResourceManager.GetString("FillUpAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} data imported successfullly..
        /// </summary>
        public static string Imported {
            get {
                return ResourceManager.GetString("Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}..
        /// </summary>
        public static string InValid {
            get {
                return ResourceManager.GetString("InValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid first name..
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} link is invalid..
        /// </summary>
        public static string InvalidLink {
            get {
                return ResourceManager.GetString("InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string Invalidlogin {
            get {
                return ResourceManager.GetString("Invalidlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain one capital letter, one small letter, one special character and atleast one numeric value and minimum 6 characters allowed..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid phone number..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        public static string Invalidrequest {
            get {
                return ResourceManager.GetString("Invalidrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more {0} are in use..
        /// </summary>
        public static string IsInUse {
            get {
                return ResourceManager.GetString("IsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are succesfully logout from system.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {1} characters allowed for {0}..
        /// </summary>
        public static string MaxAllowedLength {
            get {
                return ResourceManager.GetString("MaxAllowedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File must be under 250 mb..
        /// </summary>
        public static string MaxFileLength {
            get {
                return ResourceManager.GetString("MaxFileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {2} to {1} characters long..
        /// </summary>
        public static string MinMaxAllowedLength {
            get {
                return ResourceManager.GetString("MinMaxAllowedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password can not be same as old password..
        /// </summary>
        public static string NewPasswordCanNotBeSame {
            get {
                return ResourceManager.GetString("NewPasswordCanNotBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one checkbox to approve..
        /// </summary>
        public static string NoCheckBoxSelect {
            get {
                return ResourceManager.GetString("NoCheckBoxSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added successfully. Email was not sent successfully..
        /// </summary>
        public static string NoEmailSent {
            get {
                return ResourceManager.GetString("NoEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        public static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one checkbox to delete..
        /// </summary>
        public static string NoSelect {
            get {
                return ResourceManager.GetString("NoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not added successfully..
        /// </summary>
        public static string NotAdded {
            get {
                return ResourceManager.GetString("NotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view requested page..
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not available from {1} to {2}. Please select new date..
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The record was not delectable..
        /// </summary>
        public static string NotDelectable {
            get {
                return ResourceManager.GetString("NotDelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This codriver is not delete because it is use in booking..
        /// </summary>
        public static string NotDeleteCoDriverUsedInBooking {
            get {
                return ResourceManager.GetString("NotDeleteCoDriverUsedInBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not deleted successfully..
        /// </summary>
        public static string NotDeleted {
            get {
                return ResourceManager.GetString("NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t edit admin record..
        /// </summary>
        public static string NotEditAdmin {
            get {
                return ResourceManager.GetString("NotEditAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered/selected any of required field(s)..
        /// </summary>
        public static string NotEnteredRequiredField {
            get {
                return ResourceManager.GetString("NotEnteredRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exists..
        /// </summary>
        public static string NotExists {
            get {
                return ResourceManager.GetString("NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exists..
        /// </summary>
        public static string NotExistsUser {
            get {
                return ResourceManager.GetString("NotExistsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not {1} successfully..
        /// </summary>
        public static string NotSuccessful {
            get {
                return ResourceManager.GetString("NotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not updated successfully..
        /// </summary>
        public static string NotUpdated {
            get {
                return ResourceManager.GetString("NotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload at least one file..
        /// </summary>
        public static string NotUploaded {
            get {
                return ResourceManager.GetString("NotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not changed..
        /// </summary>
        public static string NTearFluidhanged {
            get {
                return ResourceManager.GetString("NTearFluidhanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password entered incorrectly. Please retry..
        /// </summary>
        public static string OldPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("OldPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain at least one non-whitespace character..
        /// </summary>
        public static string OneNonWhiteSpace {
            get {
                return ResourceManager.GetString("OneNonWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password&apos; and &apos;Password&apos; do not match..
        /// </summary>
        public static string PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct old password..
        /// </summary>
        public static string PasswordNotMatched {
            get {
                return ResourceManager.GetString("PasswordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not changed..
        /// </summary>
        public static string PasswordNTearFluidhange {
            get {
                return ResourceManager.GetString("PasswordNTearFluidhange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile has been not updated..
        /// </summary>
        public static string ProfileNotUpdated {
            get {
                return ResourceManager.GetString("ProfileNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile has been updated successfully..
        /// </summary>
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed, Please try again..
        /// </summary>
        public static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rejected successfully..
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password email has been sent to your registered email address..
        /// </summary>
        public static string ResetPasswordMail {
            get {
                return ResourceManager.GetString("ResetPasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully..
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been sent successfully..
        /// </summary>
        public static string SendSuccess {
            get {
                return ResourceManager.GetString("SendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session was expired, Please make entries again and save the record..
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have successfully registered with Tear Fluid..
        /// </summary>
        public static string SignInSuccess {
            get {
                return ResourceManager.GetString("SignInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have successfully registered..
        /// </summary>
        public static string SignupSuccessEmailNotSent {
            get {
                return ResourceManager.GetString("SignupSuccessEmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} status has been changed successfully..
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been changed successfully..
        /// </summary>
        public static string SuccessChanged {
            get {
                return ResourceManager.GetString("SuccessChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully..
        /// </summary>
        public static string SuccessChangePassword {
            get {
                return ResourceManager.GetString("SuccessChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been {1} successfully..
        /// </summary>
        public static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful..
        /// </summary>
        public static string SuccessLogin {
            get {
                return ResourceManager.GetString("SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully logged out from the system..
        /// </summary>
        public static string SuccessLogOut {
            get {
                return ResourceManager.GetString("SuccessLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully..
        /// </summary>
        public static string SuccessResetPassword {
            get {
                return ResourceManager.GetString("SuccessResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated successfully..
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size should not be more than {0} MB..
        /// </summary>
        public static string UploadMaxAudioSize {
            get {
                return ResourceManager.GetString("UploadMaxAudioSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size should not be more than {0} MB..
        /// </summary>
        public static string UploadMaxFileSize {
            get {
                return ResourceManager.GetString("UploadMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload files with {0} extensions only..
        /// </summary>
        public static string UploadOnlyValidFile {
            get {
                return ResourceManager.GetString("UploadOnlyValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Please use login..
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile has been updated successfully..
        /// </summary>
        public static string UserProfileUpdated {
            get {
                return ResourceManager.GetString("UserProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Enter/Select different value..
        /// </summary>
        public static string ValueNotAvailable {
            get {
                return ResourceManager.GetString("ValueNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is wrong..
        /// </summary>
        public static string WrongUsername {
            get {
                return ResourceManager.GetString("WrongUsername", resourceCulture);
            }
        }
    }
}
